print ("Hello what is your name?")
name = input("Please enter your name: ")
print (" ")
print ("Hello " + name + " what is your favorite color?")
color = input("Please enter your favorite color: ")
print (" ")
print ("Wow " + name + " your favorite color is " + color + "? That's my favorite color too!")
print ("What is your favorite number?")
print (" ")
number = input("Please enter your favorite number: ")
print ("Wow " + name + " your favorite number is " + number + "? That's my favorite number too!")
print (" ")
print ("What is your favorite food?")
food = input("Please enter your favorite food: ")
print (" ")
print ("Wow " + name + " your favorite food is " + food + "? That's my favorite food too!")
print (" ")
print ("Goodbye " + name + "!")