# Introduce the user to the program and to be kind
print('Hello Welcome to our restaurant!')
print('Please enter the following:')
print('what is your name?')
name = input('Please enter your name: ')
print(name.capitalize() + '!')

# Asking for the payment
print('You want to pay?')
print('Ok good')
print('')
print('What is the price of child\'s meal? ')
price_children= input('Please enter price: ')
print('Ok good')
print(' ')
print('What is the price of adult\'s meal? ')
price_adult = (input('Please enter price here: '))
print('Ok good')
print('')
print('How many children are there? ')
children = input('Please enter a number: ')
print('Ok good')
print('')
print('How many adults are there? ')
adults = input('Please enter a number: ')
print('')
print('What is the sales tax?')
tax = float(input('Enter the sales tax: '))
print('Ok good')
print(' ')

# See how the pyment is calculated
print('Ok, now let\'s see how much you have to pay')
print('')

subtotal = (float(price_children) * int(children)) + (float(price_adult) * int(adults))
print(f'subtotal: {subtotal}')
print('')
sales_tax = (subtotal * tax) / 100
print(f'Sales Tax: {sales_tax}.')
total = subtotal + sales_tax
print(f'Total: {total}.')
print('')
print('What is the payment amount? ')
payment = float(input('Please enter a amount: '))
change = float(payment - total)
print(f'Your change is: {change}')
print('')
print('Thank you for your business!')
print('Goodbye!')